### ISSUE TITLE
save_table

### ISSUE THREAD

**Issue by julianstar88** [CANTERhm/Canter_Matlab_Library#4]
schau mal basti, ich hab in der save_table die möglichkeit hinzugefügt auch structs als Input zuzulassen. Dafür sind nur zwei kleine Änderungen notwendig gewesen (sie die Datei im Anhang):

- Gleich am Anfang, wo entschieden wird, was "varargin{1}" ist. 
- wenn die input argumente dem parser übergeben werden, musste eine kleine Modifikation bei 
  den bedingung durchgeführt werden.

Im Prinzip läufts es ab, als wenn der erste inputparameter eine "Tabelle" ist. Das "struct-object" wird mittels "struct2table" direkt in eine Tabelle umgewandelt.

kleiner Tipp: wenn du das textfile mit Notepad++ öffnest, kannst du die Sprache in Matlab ändern

[save_table_new.txt](https://github.com/CANTERhm/Canter_Matlab_Library/files/3281065/save_table_new.txt)

**Comment by BastianHartmann** [comment]
Die Erweiterungen der save_table Funktion wurden eingearbeitet.
